# Generated by Django 3.2 on 2022-10-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_dzen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
