# Generated by Django 3.2 on 2022-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_dzen', '0002_comment_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, null=True, verbose_name='Name'),
        ),
    ]
