# Generated by Django 3.2 on 2022-10-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_dzen', '0004_auto_20221030_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(help_text='Если вы незарегестнрированный пользователь укажите временный username', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_number',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
