# Generated by Django 3.2 on 2022-10-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_dzen', '0005_auto_20221031_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, help_text='Если вы незарегестнрированный пользователь укажите временный username', max_length=100, verbose_name='Name'),
        ),
    ]
